// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/protos/questions.proto

package org.protobee.examples.protos;

public final class BroadcasterProtos {
  private BroadcasterProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    QUESTION(0, 0),
    ANSWER(1, 1),
    ;
    
    public static final int QUESTION_VALUE = 0;
    public static final int ANSWER_VALUE = 1;
    
    
    public final int getNumber() { return value; }
    
    public static MessageType valueOf(int value) {
      switch (value) {
        case 0: return QUESTION;
        case 1: return ANSWER;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.protobee.examples.protos.BroadcasterProtos.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final MessageType[] VALUES = {
      QUESTION, ANSWER, 
    };
    
    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private MessageType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:org.protobee.examples.protos.MessageType)
  }
  
  public interface HeaderOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required bytes id = 1;
    boolean hasId();
    com.google.protobuf.ByteString getId();
    
    // required uint32 ttl = 2;
    boolean hasTtl();
    int getTtl();
    
    // required uint32 hops = 3;
    boolean hasHops();
    int getHops();
    
    // required .org.protobee.examples.protos.MessageType type = 4;
    boolean hasType();
    org.protobee.examples.protos.BroadcasterProtos.MessageType getType();
  }
  public static final class Header extends
      com.google.protobuf.GeneratedMessage
      implements HeaderOrBuilder {
    // Use Header.newBuilder() to construct.
    private Header(Builder builder) {
      super(builder);
    }
    private Header(boolean noInit) {}
    
    private static final Header defaultInstance;
    public static Header getDefaultInstance() {
      return defaultInstance;
    }
    
    public Header getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.protobee.examples.protos.BroadcasterProtos.internal_static_org_protobee_examples_protos_Header_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.protobee.examples.protos.BroadcasterProtos.internal_static_org_protobee_examples_protos_Header_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required bytes id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.google.protobuf.ByteString getId() {
      return id_;
    }
    
    // required uint32 ttl = 2;
    public static final int TTL_FIELD_NUMBER = 2;
    private int ttl_;
    public boolean hasTtl() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getTtl() {
      return ttl_;
    }
    
    // required uint32 hops = 3;
    public static final int HOPS_FIELD_NUMBER = 3;
    private int hops_;
    public boolean hasHops() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getHops() {
      return hops_;
    }
    
    // required .org.protobee.examples.protos.MessageType type = 4;
    public static final int TYPE_FIELD_NUMBER = 4;
    private org.protobee.examples.protos.BroadcasterProtos.MessageType type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public org.protobee.examples.protos.BroadcasterProtos.MessageType getType() {
      return type_;
    }
    
    private void initFields() {
      id_ = com.google.protobuf.ByteString.EMPTY;
      ttl_ = 0;
      hops_ = 0;
      type_ = org.protobee.examples.protos.BroadcasterProtos.MessageType.QUESTION;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTtl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHops()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, ttl_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, hops_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, type_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, ttl_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, hops_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, type_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.protobee.examples.protos.BroadcasterProtos.Header parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.protobee.examples.protos.BroadcasterProtos.Header parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.protobee.examples.protos.BroadcasterProtos.Header parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.protobee.examples.protos.BroadcasterProtos.Header parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.protobee.examples.protos.BroadcasterProtos.Header parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.protobee.examples.protos.BroadcasterProtos.Header parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.protobee.examples.protos.BroadcasterProtos.Header parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.protobee.examples.protos.BroadcasterProtos.Header parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.protobee.examples.protos.BroadcasterProtos.Header parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.protobee.examples.protos.BroadcasterProtos.Header parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.protobee.examples.protos.BroadcasterProtos.Header prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.protobee.examples.protos.BroadcasterProtos.HeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.protobee.examples.protos.BroadcasterProtos.internal_static_org_protobee_examples_protos_Header_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.protobee.examples.protos.BroadcasterProtos.internal_static_org_protobee_examples_protos_Header_fieldAccessorTable;
      }
      
      // Construct using org.protobee.examples.protos.BroadcasterProtos.Header.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        ttl_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        hops_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = org.protobee.examples.protos.BroadcasterProtos.MessageType.QUESTION;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.protobee.examples.protos.BroadcasterProtos.Header.getDescriptor();
      }
      
      public org.protobee.examples.protos.BroadcasterProtos.Header getDefaultInstanceForType() {
        return org.protobee.examples.protos.BroadcasterProtos.Header.getDefaultInstance();
      }
      
      public org.protobee.examples.protos.BroadcasterProtos.Header build() {
        org.protobee.examples.protos.BroadcasterProtos.Header result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.protobee.examples.protos.BroadcasterProtos.Header buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.protobee.examples.protos.BroadcasterProtos.Header result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.protobee.examples.protos.BroadcasterProtos.Header buildPartial() {
        org.protobee.examples.protos.BroadcasterProtos.Header result = new org.protobee.examples.protos.BroadcasterProtos.Header(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ttl_ = ttl_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.hops_ = hops_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.protobee.examples.protos.BroadcasterProtos.Header) {
          return mergeFrom((org.protobee.examples.protos.BroadcasterProtos.Header)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.protobee.examples.protos.BroadcasterProtos.Header other) {
        if (other == org.protobee.examples.protos.BroadcasterProtos.Header.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasTtl()) {
          setTtl(other.getTtl());
        }
        if (other.hasHops()) {
          setHops(other.getHops());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasTtl()) {
          
          return false;
        }
        if (!hasHops()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              ttl_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              hops_ = input.readUInt32();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              org.protobee.examples.protos.BroadcasterProtos.MessageType value = org.protobee.examples.protos.BroadcasterProtos.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                type_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required bytes id = 1;
      private com.google.protobuf.ByteString id_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.google.protobuf.ByteString getId() {
        return id_;
      }
      public Builder setId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      
      // required uint32 ttl = 2;
      private int ttl_ ;
      public boolean hasTtl() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getTtl() {
        return ttl_;
      }
      public Builder setTtl(int value) {
        bitField0_ |= 0x00000002;
        ttl_ = value;
        onChanged();
        return this;
      }
      public Builder clearTtl() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ttl_ = 0;
        onChanged();
        return this;
      }
      
      // required uint32 hops = 3;
      private int hops_ ;
      public boolean hasHops() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getHops() {
        return hops_;
      }
      public Builder setHops(int value) {
        bitField0_ |= 0x00000004;
        hops_ = value;
        onChanged();
        return this;
      }
      public Builder clearHops() {
        bitField0_ = (bitField0_ & ~0x00000004);
        hops_ = 0;
        onChanged();
        return this;
      }
      
      // required .org.protobee.examples.protos.MessageType type = 4;
      private org.protobee.examples.protos.BroadcasterProtos.MessageType type_ = org.protobee.examples.protos.BroadcasterProtos.MessageType.QUESTION;
      public boolean hasType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public org.protobee.examples.protos.BroadcasterProtos.MessageType getType() {
        return type_;
      }
      public Builder setType(org.protobee.examples.protos.BroadcasterProtos.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = org.protobee.examples.protos.BroadcasterProtos.MessageType.QUESTION;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.protobee.examples.protos.Header)
    }
    
    static {
      defaultInstance = new Header(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.protobee.examples.protos.Header)
  }
  
  public interface QuestionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string question = 1;
    boolean hasQuestion();
    String getQuestion();
  }
  public static final class Question extends
      com.google.protobuf.GeneratedMessage
      implements QuestionOrBuilder {
    // Use Question.newBuilder() to construct.
    private Question(Builder builder) {
      super(builder);
    }
    private Question(boolean noInit) {}
    
    private static final Question defaultInstance;
    public static Question getDefaultInstance() {
      return defaultInstance;
    }
    
    public Question getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.protobee.examples.protos.BroadcasterProtos.internal_static_org_protobee_examples_protos_Question_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.protobee.examples.protos.BroadcasterProtos.internal_static_org_protobee_examples_protos_Question_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string question = 1;
    public static final int QUESTION_FIELD_NUMBER = 1;
    private java.lang.Object question_;
    public boolean hasQuestion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getQuestion() {
      java.lang.Object ref = question_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          question_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getQuestionBytes() {
      java.lang.Object ref = question_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        question_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      question_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasQuestion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getQuestionBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getQuestionBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.protobee.examples.protos.BroadcasterProtos.Question parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.protobee.examples.protos.BroadcasterProtos.Question parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.protobee.examples.protos.BroadcasterProtos.Question parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.protobee.examples.protos.BroadcasterProtos.Question parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.protobee.examples.protos.BroadcasterProtos.Question parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.protobee.examples.protos.BroadcasterProtos.Question parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.protobee.examples.protos.BroadcasterProtos.Question parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.protobee.examples.protos.BroadcasterProtos.Question parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.protobee.examples.protos.BroadcasterProtos.Question parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.protobee.examples.protos.BroadcasterProtos.Question parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.protobee.examples.protos.BroadcasterProtos.Question prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.protobee.examples.protos.BroadcasterProtos.QuestionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.protobee.examples.protos.BroadcasterProtos.internal_static_org_protobee_examples_protos_Question_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.protobee.examples.protos.BroadcasterProtos.internal_static_org_protobee_examples_protos_Question_fieldAccessorTable;
      }
      
      // Construct using org.protobee.examples.protos.BroadcasterProtos.Question.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        question_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.protobee.examples.protos.BroadcasterProtos.Question.getDescriptor();
      }
      
      public org.protobee.examples.protos.BroadcasterProtos.Question getDefaultInstanceForType() {
        return org.protobee.examples.protos.BroadcasterProtos.Question.getDefaultInstance();
      }
      
      public org.protobee.examples.protos.BroadcasterProtos.Question build() {
        org.protobee.examples.protos.BroadcasterProtos.Question result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.protobee.examples.protos.BroadcasterProtos.Question buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.protobee.examples.protos.BroadcasterProtos.Question result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.protobee.examples.protos.BroadcasterProtos.Question buildPartial() {
        org.protobee.examples.protos.BroadcasterProtos.Question result = new org.protobee.examples.protos.BroadcasterProtos.Question(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.question_ = question_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.protobee.examples.protos.BroadcasterProtos.Question) {
          return mergeFrom((org.protobee.examples.protos.BroadcasterProtos.Question)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.protobee.examples.protos.BroadcasterProtos.Question other) {
        if (other == org.protobee.examples.protos.BroadcasterProtos.Question.getDefaultInstance()) return this;
        if (other.hasQuestion()) {
          setQuestion(other.getQuestion());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasQuestion()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              question_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string question = 1;
      private java.lang.Object question_ = "";
      public boolean hasQuestion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getQuestion() {
        java.lang.Object ref = question_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          question_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setQuestion(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        question_ = value;
        onChanged();
        return this;
      }
      public Builder clearQuestion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        question_ = getDefaultInstance().getQuestion();
        onChanged();
        return this;
      }
      void setQuestion(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        question_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:org.protobee.examples.protos.Question)
    }
    
    static {
      defaultInstance = new Question(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.protobee.examples.protos.Question)
  }
  
  public interface AnswerOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string answer = 1;
    boolean hasAnswer();
    String getAnswer();
  }
  public static final class Answer extends
      com.google.protobuf.GeneratedMessage
      implements AnswerOrBuilder {
    // Use Answer.newBuilder() to construct.
    private Answer(Builder builder) {
      super(builder);
    }
    private Answer(boolean noInit) {}
    
    private static final Answer defaultInstance;
    public static Answer getDefaultInstance() {
      return defaultInstance;
    }
    
    public Answer getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.protobee.examples.protos.BroadcasterProtos.internal_static_org_protobee_examples_protos_Answer_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.protobee.examples.protos.BroadcasterProtos.internal_static_org_protobee_examples_protos_Answer_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string answer = 1;
    public static final int ANSWER_FIELD_NUMBER = 1;
    private java.lang.Object answer_;
    public boolean hasAnswer() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getAnswer() {
      java.lang.Object ref = answer_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          answer_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAnswerBytes() {
      java.lang.Object ref = answer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        answer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      answer_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasAnswer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getAnswerBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getAnswerBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.protobee.examples.protos.BroadcasterProtos.Answer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.protobee.examples.protos.BroadcasterProtos.Answer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.protobee.examples.protos.BroadcasterProtos.Answer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.protobee.examples.protos.BroadcasterProtos.Answer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.protobee.examples.protos.BroadcasterProtos.Answer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.protobee.examples.protos.BroadcasterProtos.Answer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.protobee.examples.protos.BroadcasterProtos.Answer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.protobee.examples.protos.BroadcasterProtos.Answer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.protobee.examples.protos.BroadcasterProtos.Answer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.protobee.examples.protos.BroadcasterProtos.Answer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.protobee.examples.protos.BroadcasterProtos.Answer prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.protobee.examples.protos.BroadcasterProtos.AnswerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.protobee.examples.protos.BroadcasterProtos.internal_static_org_protobee_examples_protos_Answer_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.protobee.examples.protos.BroadcasterProtos.internal_static_org_protobee_examples_protos_Answer_fieldAccessorTable;
      }
      
      // Construct using org.protobee.examples.protos.BroadcasterProtos.Answer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        answer_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.protobee.examples.protos.BroadcasterProtos.Answer.getDescriptor();
      }
      
      public org.protobee.examples.protos.BroadcasterProtos.Answer getDefaultInstanceForType() {
        return org.protobee.examples.protos.BroadcasterProtos.Answer.getDefaultInstance();
      }
      
      public org.protobee.examples.protos.BroadcasterProtos.Answer build() {
        org.protobee.examples.protos.BroadcasterProtos.Answer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.protobee.examples.protos.BroadcasterProtos.Answer buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.protobee.examples.protos.BroadcasterProtos.Answer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.protobee.examples.protos.BroadcasterProtos.Answer buildPartial() {
        org.protobee.examples.protos.BroadcasterProtos.Answer result = new org.protobee.examples.protos.BroadcasterProtos.Answer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.answer_ = answer_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.protobee.examples.protos.BroadcasterProtos.Answer) {
          return mergeFrom((org.protobee.examples.protos.BroadcasterProtos.Answer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.protobee.examples.protos.BroadcasterProtos.Answer other) {
        if (other == org.protobee.examples.protos.BroadcasterProtos.Answer.getDefaultInstance()) return this;
        if (other.hasAnswer()) {
          setAnswer(other.getAnswer());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasAnswer()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              answer_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string answer = 1;
      private java.lang.Object answer_ = "";
      public boolean hasAnswer() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getAnswer() {
        java.lang.Object ref = answer_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          answer_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAnswer(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        answer_ = value;
        onChanged();
        return this;
      }
      public Builder clearAnswer() {
        bitField0_ = (bitField0_ & ~0x00000001);
        answer_ = getDefaultInstance().getAnswer();
        onChanged();
        return this;
      }
      void setAnswer(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        answer_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:org.protobee.examples.protos.Answer)
    }
    
    static {
      defaultInstance = new Answer(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.protobee.examples.protos.Answer)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_protobee_examples_protos_Header_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_protobee_examples_protos_Header_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_protobee_examples_protos_Question_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_protobee_examples_protos_Question_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_protobee_examples_protos_Answer_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_protobee_examples_protos_Answer_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)src/main/resources/protos/questions.pr" +
      "oto\022\034org.protobee.examples.protos\"h\n\006Hea" +
      "der\022\n\n\002id\030\001 \002(\014\022\013\n\003ttl\030\002 \002(\r\022\014\n\004hops\030\003 \002" +
      "(\r\0227\n\004type\030\004 \002(\0162).org.protobee.examples" +
      ".protos.MessageType\"\034\n\010Question\022\020\n\010quest" +
      "ion\030\001 \002(\t\"\030\n\006Answer\022\016\n\006answer\030\001 \002(\t*\'\n\013M" +
      "essageType\022\014\n\010QUESTION\020\000\022\n\n\006ANSWER\020\001B1\n\034" +
      "org.protobee.examples.protosB\021Broadcaste" +
      "rProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_protobee_examples_protos_Header_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_protobee_examples_protos_Header_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_protobee_examples_protos_Header_descriptor,
              new java.lang.String[] { "Id", "Ttl", "Hops", "Type", },
              org.protobee.examples.protos.BroadcasterProtos.Header.class,
              org.protobee.examples.protos.BroadcasterProtos.Header.Builder.class);
          internal_static_org_protobee_examples_protos_Question_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_org_protobee_examples_protos_Question_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_protobee_examples_protos_Question_descriptor,
              new java.lang.String[] { "Question", },
              org.protobee.examples.protos.BroadcasterProtos.Question.class,
              org.protobee.examples.protos.BroadcasterProtos.Question.Builder.class);
          internal_static_org_protobee_examples_protos_Answer_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_org_protobee_examples_protos_Answer_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_protobee_examples_protos_Answer_descriptor,
              new java.lang.String[] { "Answer", },
              org.protobee.examples.protos.BroadcasterProtos.Answer.class,
              org.protobee.examples.protos.BroadcasterProtos.Answer.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
