// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: emotion.proto

package org.protobee.examples.protos;

public final class EmotionProtos {
  private EmotionProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EmotionMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .protobee.Header header = 1;
    boolean hasHeader();
    org.protobee.examples.protos.Common.Header getHeader();
    org.protobee.examples.protos.Common.HeaderOrBuilder getHeaderOrBuilder();
    
    // required .protobee.EmotionMessage.Type emotion = 2;
    boolean hasEmotion();
    org.protobee.examples.protos.EmotionProtos.EmotionMessage.Type getEmotion();
  }
  public static final class EmotionMessage extends
      com.google.protobuf.GeneratedMessage
      implements EmotionMessageOrBuilder {
    // Use EmotionMessage.newBuilder() to construct.
    private EmotionMessage(Builder builder) {
      super(builder);
    }
    private EmotionMessage(boolean noInit) {}
    
    private static final EmotionMessage defaultInstance;
    public static EmotionMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public EmotionMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.protobee.examples.protos.EmotionProtos.internal_static_protobee_EmotionMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.protobee.examples.protos.EmotionProtos.internal_static_protobee_EmotionMessage_fieldAccessorTable;
    }
    
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      AFRAID(0, 0),
      ANGRY(1, 1),
      HAPPY(2, 2),
      DISGUSTED(3, 3),
      SAD(4, 4),
      SURPRISED(5, 5),
      BLAH(6, 6),
      ;
      
      public static final int AFRAID_VALUE = 0;
      public static final int ANGRY_VALUE = 1;
      public static final int HAPPY_VALUE = 2;
      public static final int DISGUSTED_VALUE = 3;
      public static final int SAD_VALUE = 4;
      public static final int SURPRISED_VALUE = 5;
      public static final int BLAH_VALUE = 6;
      
      
      public final int getNumber() { return value; }
      
      public static Type valueOf(int value) {
        switch (value) {
          case 0: return AFRAID;
          case 1: return ANGRY;
          case 2: return HAPPY;
          case 3: return DISGUSTED;
          case 4: return SAD;
          case 5: return SURPRISED;
          case 6: return BLAH;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.protobee.examples.protos.EmotionProtos.EmotionMessage.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Type[] VALUES = {
        AFRAID, ANGRY, HAPPY, DISGUSTED, SAD, SURPRISED, BLAH, 
      };
      
      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:protobee.EmotionMessage.Type)
    }
    
    private int bitField0_;
    // required .protobee.Header header = 1;
    public static final int HEADER_FIELD_NUMBER = 1;
    private org.protobee.examples.protos.Common.Header header_;
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public org.protobee.examples.protos.Common.Header getHeader() {
      return header_;
    }
    public org.protobee.examples.protos.Common.HeaderOrBuilder getHeaderOrBuilder() {
      return header_;
    }
    
    // required .protobee.EmotionMessage.Type emotion = 2;
    public static final int EMOTION_FIELD_NUMBER = 2;
    private org.protobee.examples.protos.EmotionProtos.EmotionMessage.Type emotion_;
    public boolean hasEmotion() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public org.protobee.examples.protos.EmotionProtos.EmotionMessage.Type getEmotion() {
      return emotion_;
    }
    
    private void initFields() {
      header_ = org.protobee.examples.protos.Common.Header.getDefaultInstance();
      emotion_ = org.protobee.examples.protos.EmotionProtos.EmotionMessage.Type.AFRAID;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasHeader()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEmotion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getHeader().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, header_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, emotion_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, header_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, emotion_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.protobee.examples.protos.EmotionProtos.EmotionMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.protobee.examples.protos.EmotionProtos.EmotionMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.protobee.examples.protos.EmotionProtos.EmotionMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.protobee.examples.protos.EmotionProtos.EmotionMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.protobee.examples.protos.EmotionProtos.EmotionMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.protobee.examples.protos.EmotionProtos.EmotionMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.protobee.examples.protos.EmotionProtos.EmotionMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.protobee.examples.protos.EmotionProtos.EmotionMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.protobee.examples.protos.EmotionProtos.EmotionMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.protobee.examples.protos.EmotionProtos.EmotionMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.protobee.examples.protos.EmotionProtos.EmotionMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.protobee.examples.protos.EmotionProtos.EmotionMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.protobee.examples.protos.EmotionProtos.internal_static_protobee_EmotionMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.protobee.examples.protos.EmotionProtos.internal_static_protobee_EmotionMessage_fieldAccessorTable;
      }
      
      // Construct using org.protobee.examples.protos.EmotionProtos.EmotionMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHeaderFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = org.protobee.examples.protos.Common.Header.getDefaultInstance();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        emotion_ = org.protobee.examples.protos.EmotionProtos.EmotionMessage.Type.AFRAID;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.protobee.examples.protos.EmotionProtos.EmotionMessage.getDescriptor();
      }
      
      public org.protobee.examples.protos.EmotionProtos.EmotionMessage getDefaultInstanceForType() {
        return org.protobee.examples.protos.EmotionProtos.EmotionMessage.getDefaultInstance();
      }
      
      public org.protobee.examples.protos.EmotionProtos.EmotionMessage build() {
        org.protobee.examples.protos.EmotionProtos.EmotionMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.protobee.examples.protos.EmotionProtos.EmotionMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.protobee.examples.protos.EmotionProtos.EmotionMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.protobee.examples.protos.EmotionProtos.EmotionMessage buildPartial() {
        org.protobee.examples.protos.EmotionProtos.EmotionMessage result = new org.protobee.examples.protos.EmotionProtos.EmotionMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.emotion_ = emotion_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.protobee.examples.protos.EmotionProtos.EmotionMessage) {
          return mergeFrom((org.protobee.examples.protos.EmotionProtos.EmotionMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.protobee.examples.protos.EmotionProtos.EmotionMessage other) {
        if (other == org.protobee.examples.protos.EmotionProtos.EmotionMessage.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.hasEmotion()) {
          setEmotion(other.getEmotion());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasHeader()) {
          
          return false;
        }
        if (!hasEmotion()) {
          
          return false;
        }
        if (!getHeader().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              org.protobee.examples.protos.Common.Header.Builder subBuilder = org.protobee.examples.protos.Common.Header.newBuilder();
              if (hasHeader()) {
                subBuilder.mergeFrom(getHeader());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setHeader(subBuilder.buildPartial());
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              org.protobee.examples.protos.EmotionProtos.EmotionMessage.Type value = org.protobee.examples.protos.EmotionProtos.EmotionMessage.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                emotion_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .protobee.Header header = 1;
      private org.protobee.examples.protos.Common.Header header_ = org.protobee.examples.protos.Common.Header.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.protobee.examples.protos.Common.Header, org.protobee.examples.protos.Common.Header.Builder, org.protobee.examples.protos.Common.HeaderOrBuilder> headerBuilder_;
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public org.protobee.examples.protos.Common.Header getHeader() {
        if (headerBuilder_ == null) {
          return header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      public Builder setHeader(org.protobee.examples.protos.Common.Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setHeader(
          org.protobee.examples.protos.Common.Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeHeader(org.protobee.examples.protos.Common.Header value) {
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              header_ != org.protobee.examples.protos.Common.Header.getDefaultInstance()) {
            header_ =
              org.protobee.examples.protos.Common.Header.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = org.protobee.examples.protos.Common.Header.getDefaultInstance();
          onChanged();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public org.protobee.examples.protos.Common.Header.Builder getHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      public org.protobee.examples.protos.Common.HeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          org.protobee.examples.protos.Common.Header, org.protobee.examples.protos.Common.Header.Builder, org.protobee.examples.protos.Common.HeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.protobee.examples.protos.Common.Header, org.protobee.examples.protos.Common.Header.Builder, org.protobee.examples.protos.Common.HeaderOrBuilder>(
                  header_,
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }
      
      // required .protobee.EmotionMessage.Type emotion = 2;
      private org.protobee.examples.protos.EmotionProtos.EmotionMessage.Type emotion_ = org.protobee.examples.protos.EmotionProtos.EmotionMessage.Type.AFRAID;
      public boolean hasEmotion() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public org.protobee.examples.protos.EmotionProtos.EmotionMessage.Type getEmotion() {
        return emotion_;
      }
      public Builder setEmotion(org.protobee.examples.protos.EmotionProtos.EmotionMessage.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        emotion_ = value;
        onChanged();
        return this;
      }
      public Builder clearEmotion() {
        bitField0_ = (bitField0_ & ~0x00000002);
        emotion_ = org.protobee.examples.protos.EmotionProtos.EmotionMessage.Type.AFRAID;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:protobee.EmotionMessage)
    }
    
    static {
      defaultInstance = new EmotionMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protobee.EmotionMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobee_EmotionMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobee_EmotionMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\remotion.proto\022\010protobee\032\014common.proto\"" +
      "\275\001\n\016EmotionMessage\022 \n\006header\030\001 \002(\0132\020.pro" +
      "tobee.Header\022.\n\007emotion\030\002 \002(\0162\035.protobee" +
      ".EmotionMessage.Type\"Y\n\004Type\022\n\n\006AFRAID\020\000" +
      "\022\t\n\005ANGRY\020\001\022\t\n\005HAPPY\020\002\022\r\n\tDISGUSTED\020\003\022\007\n" +
      "\003SAD\020\004\022\r\n\tSURPRISED\020\005\022\010\n\004BLAH\020\006B-\n\034org.p" +
      "rotobee.examples.protosB\rEmotionProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protobee_EmotionMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protobee_EmotionMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobee_EmotionMessage_descriptor,
              new java.lang.String[] { "Header", "Emotion", },
              org.protobee.examples.protos.EmotionProtos.EmotionMessage.class,
              org.protobee.examples.protos.EmotionProtos.EmotionMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.protobee.examples.protos.Common.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
